/**
 * Step 1 of the store-screenshot pipeline: capture raw material from the real extension.
 *
 * Chromium is launched with the unpacked build loaded, a real Spanish Wikipedia article is
 * opened, a real word is selected with a real double-click, and the extension's own content
 * script hands that selection to the side panel exactly as it does for a user. The card is
 * then generated by the real generation path and every capture below is a screenshot of
 * that running UI — nothing here draws extension chrome of its own.
 *
 * The side panel cannot be driven through Chrome's own UI from Playwright, so it is opened
 * directly as a page at chrome-extension://<id>/sidepanel.html. That is the same document
 * Chrome renders in the panel, at a panel-sized viewport.
 *
 *   node scripts/store-shots/capture.js [--keep-open] [--only=main,review,page2]
 */

const fs = require('fs');
const os = require('os');
const path = require('path');
const { chromium } = require('playwright');

const {
  CONTENT, SECOND_PAGE, paths, CAPTURE, WINDOW,
} = require('./config');

const PANEL_VIEWPORT = CAPTURE.panel.css;
const PAGE_VIEWPORT = CAPTURE.page.css;

const argv = process.argv.slice(2);
const flag = (name) => argv.some((a) => a === `--${name}`);
const option = (name, fallback) => {
  const hit = argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};
const only = option('only', 'main,review,page2').split(',').map((s) => s.trim());

const log = (...args) => console.log('[capture]', ...args);

const raw = (name) => path.join(paths.raw, name);

/**
 * An OpenAI key turns on the extension's full create screen, which is the only path that
 * draws an illustration onto the card — the free trial server returns text only. Read from
 * the environment or from a key file so it never has to be typed into a command line.
 */
function readOpenAiKey() {
  const fromEnv = (process.env.OPENAI_API_KEY || '').trim();
  if (fromEnv) return fromEnv;

  const keyFile = process.env.VAULTO_OPENAI_KEY_FILE
    || path.join(os.homedir(), '.config', 'vaulto', 'openai.key');
  try {
    const fromFile = fs.readFileSync(keyFile, 'utf8').trim();
    if (fromFile) {
      log('using the OpenAI key at', keyFile);
      return fromFile;
    }
  } catch { /* no key file: the trial path below still produces a real card */ }
  return null;
}

const OPENAI_KEY = readOpenAiKey();

/* ------------------------------------------------------------------ browser ---- */

async function launch() {
  fs.mkdirSync(paths.raw, { recursive: true });
  if (!fs.existsSync(path.join(paths.extension, 'manifest.json'))) {
    throw new Error(`No built extension at ${paths.extension} — run \`npm run build\` first.`);
  }

  // A throwaway profile per run: no bookmarks bar, no other extensions, no history, and
  // nothing of the user's own in any frame.
  const userDataDir = fs.mkdtempSync(path.join(os.tmpdir(), 'vaulto-shots-'));
  const ctx = await chromium.launchPersistentContext(userDataDir, {
    headless: false,
    args: [
      `--disable-extensions-except=${paths.extension}`,
      `--load-extension=${paths.extension}`,
      '--hide-scrollbars',
      '--disable-features=Translate,MediaRouter',
      '--no-first-run',
    ],
    viewport: { width: 1440, height: 900 },
    deviceScaleFactor: CAPTURE.deviceScaleFactor,
    locale: 'en-US',
    colorScheme: 'light',
  });

  let [worker] = ctx.serviceWorkers();
  if (!worker) worker = await ctx.waitForEvent('serviceworker', { timeout: 30_000 });
  const extensionId = new URL(worker.url()).host;
  log('extension id', extensionId);

  return { ctx, worker, extensionId, userDataDir };
}

/**
 * Writes the extension's own persisted settings before the panel boots, so the panel comes
 * up already translating into the language these frames advertise. Same key and same shape
 * the extension writes itself (services/settingsPersistence.ts).
 */
async function seedSettings(worker, extra = {}) {
  await worker.evaluate(async ({ target, key, extra: more }) => {
    await chrome.storage.local.set({
      vaulto_extension_settings_v1: {
        translateToLanguage: target,
        sourceLanguage: 'es',
        shouldGenerateImage: true,
        // 'always' rather than 'smart': a screenshot cannot be left to the model's
        // judgement about whether this particular word deserves a picture.
        imageGenerationMode: key ? 'always' : 'smart',
        ...more,
      },
      // Same key and shape as services/apiKeyStorage.ts. With a key present the panel
      // shows the full create screen; without one it shows the first-run screen, whose
      // cards come from Vaulto's own server and carry no illustration.
      ...(key ? { anki_api_keys_v1: { openai: key, anki: '' } } : {}),
    });
  }, { target: CONTENT.targetLanguage, key: OPENAI_KEY, extra });
}

/* --------------------------------------------------------------------- page ---- */

/** Hides the bits of Wikipedia chrome that read as clutter in a 840px-wide frame. */
async function tidyWikipedia(page) {
  // Citation superscripts are part of the sentence as far as the DOM is concerned, so a
  // selection made next to one carries "[1]" into the card. They are taken out of the
  // document rather than merely hidden, because textContent ignores `display: none`.
  await page.evaluate(() => {
    document.querySelectorAll('sup.reference, .mw-ref, .reference').forEach((el) => el.remove());
  });
  await page.addStyleTag({
    content: `
      .vector-header-container, #siteNotice, .mw-indicator, .vector-sticky-pinned-container,
      .vector-page-toolbar, #vector-page-titlebar-toc, .vector-dropdown, .mw-editsection,
      .vector-column-start, .vector-column-end, #footer, .navbox, .vector-body-before-content,
      .cdx-button, .vector-sticky-header { display: none !important; }
      /* The hidden sidebar leaves its space behind in the flex row, which pushes the
         article off-centre and leaves a dead gutter down the left of the frame. */
      .mw-page-container-inner { display: block !important; }
      .mw-content-container { max-width: 900px !important; margin: 0 auto !important; }
      .mw-page-container, .vector-body { margin: 0 auto !important; }
      body { padding-top: 8px !important; }
    `,
  });
}

/**
 * Selects a real word on the page the way a reader does, which is what makes the
 * extension's content script fire its selection message. Returns the text the page reports
 * as selected, so the caller can assert it is the word we meant rather than discovering
 * later that the card was built from something else.
 */
async function selectWordOnPage(page, word, sentenceFragment) {
  const box = await page.evaluate(({ word: w, fragment }) => {
    // A sentence is split across several text nodes (bold lead terms, links) and, in a
    // plain HTML book, across source line breaks — so it is matched on a block element
    // with whitespace collapsed, and the word is then found inside that block's text
    // nodes, where it is never itself broken up.
    const flatten = (value) => (value || '').replace(/\s+/g, ' ').trim();
    const wanted = flatten(fragment);
    const blocks = Array.from(document.querySelectorAll('.mw-parser-output p, p, li, div'));
    const block = blocks
      .filter((el) => !el.querySelector('p, li'))
      .find((el) => flatten(el.textContent).includes(wanted));
    if (!block) return null;

    const walker = document.createTreeWalker(block, NodeFilter.SHOW_TEXT);
    let node;
    while ((node = walker.nextNode())) {
      // Double-clicking a word inside a link follows the link, which is what a reader
      // would get too — so the word has to be plain text, not a wikilink.
      if (node.parentElement.closest('a')) continue;
      const at = (node.textContent || '').indexOf(w);
      if (at === -1) continue;
      const range = document.createRange();
      range.setStart(node, at);
      range.setEnd(node, at + w.length);
      if (!range.getBoundingClientRect().width) continue;
      block.scrollIntoView({ block: 'center' });
      const rect = range.getBoundingClientRect();
      return { x: rect.left, y: rect.top, width: rect.width, height: rect.height };
    }
    return null;
  }, { word, fragment: sentenceFragment });

  if (!box) {
    throw new Error(`"${word}" was not found inside "${sentenceFragment}" on ${page.url()}`);
  }

  // A double-click is both what a reader actually does to pick one word and the steadier
  // gesture to automate: a drag across the glyphs can end a character short if the page
  // reflows between measuring the range and moving the mouse.
  const centre = { x: box.x + box.width / 2, y: box.y + box.height / 2 };
  let selected = '';
  for (let attempt = 0; attempt < 3; attempt += 1) {
    await page.mouse.dblclick(centre.x, centre.y);
    await page.waitForTimeout(250);
    selected = await page.evaluate(() => (window.getSelection() || '').toString().trim());
    if (selected === word) break;
  }
  if (selected !== word) {
    throw new Error(`selection came back as "${selected}", expected "${word}"`);
  }
  log('selected on page:', selected);
  return selected;
}

/* -------------------------------------------------------------------- panel ---- */

async function openPanel(ctx, extensionId) {
  const panel = await ctx.newPage();
  // Generation failures inside the panel are otherwise silent: the sheet just opens with
  // half a card. Surfacing them here is what makes a broken run diagnosable.
  panel.on('console', (message) => {
    if (message.type() === 'error') log('panel error:', message.text().slice(0, 300));
  });
  panel.on('pageerror', (error) => log('panel exception:', String(error).slice(0, 300)));

  // The create screen keeps its image switch in the panel's own localStorage rather than in
  // the synced settings (CreateCard.tsx: anki_image_generation_mode / the preferred-on-mode
  // in services/generationPreferences.ts). 'smart' lets the model decide whether this
  // particular word deserves a picture, which a screenshot cannot be left to; 'always' is
  // the same choice a user makes with the image chip on the create screen.
  //
  // The language pair is stored the same way. Left on auto-detect the panel guesses from
  // its own document, which is an English extension page, so the create screen comes up
  // reading "from English" — picking Spanish explicitly is what a user does in the FROM
  // selector, and it is what these frames have to show.
  if (OPENAI_KEY) {
    await panel.addInitScript(({ target }) => {
      localStorage.setItem('anki_image_generation_mode', 'always');
      localStorage.setItem('preferred_image_on_mode', 'always');
      localStorage.setItem('source_language', 'es');
      localStorage.setItem('auto_detect_language', 'false');
      localStorage.setItem('target_language', target);
    }, { target: CONTENT.targetLanguage });
  }
  await panel.setViewportSize(PANEL_VIEWPORT);
  await panel.goto(`chrome-extension://${extensionId}/sidepanel.html`);
  await panel.waitForSelector('textarea', { timeout: 30_000 });
  if (!OPENAI_KEY) {
    // The free-card counter is fetched on mount; waiting for it keeps the footer from
    // changing height mid-screenshot.
    await panel.waitForFunction(
      () => !/Checking free cards/.test(document.body.innerText),
      null,
      { timeout: 30_000 },
    ).catch(() => log('warning: free-card status did not resolve'));
  }
  return panel;
}

const panelText = (panel) => panel.innerText('body');

/** Waits for the composer to show the word the page handed over. */
async function waitForHandoff(panel, word) {
  await panel.waitForFunction(
    (w) => {
      const field = document.querySelector('textarea');
      return Boolean(field && field.value.trim() === w);
    },
    word,
    { timeout: 20_000 },
  );
  log('panel received the selection');
}

/**
 * Runs the real generation and waits for the card sheet — and then for the card to stop
 * filling in. The pipeline builds translation, examples, grammar and the illustration in
 * parallel and drops each into the sheet as it lands, so the sheet opening is the start of
 * the card, not the end of it.
 */
async function generateCard(panel) {
  await panel.getByRole('button', { name: 'Create card' }).click();
  log('generating (real request, this takes a while)…');
  await panel.waitForSelector('[role="dialog"]', { timeout: 240_000 });

  const wantImage = Boolean(OPENAI_KEY);
  try {
    await panel.waitForFunction((needsImage) => {
      const sheet = document.querySelector('[role="dialog"]');
      if (!sheet) return false;
      const hasExamples = /Examples|more examples/.test(sheet.innerText);
      const image = sheet.querySelector('img[src]');
      return hasExamples && (!needsImage || Boolean(image));
    }, wantImage, { timeout: 240_000 });
  } catch {
    log('warning: the card was still incomplete after 4 minutes — capturing it as it stands');
  }
  // The image fades in and the layout settles after the last component lands.
  await panel.waitForTimeout(2500);
  log('card sheet is open and filled');
}

const CARD = '[role="dialog"] div[style*="perspective"]';

/**
 * Frame 02's strips are taken in a shorter panel than the other frames use, and that is
 * deliberate. A taller panel makes each strip taller, and a taller strip has to be drawn
 * smaller to fit the stage: at 880px the card needs two strips and they fill two thirds of
 * the frame at 1.07x, at 760px it needs three and they fill it at about 1.2x. The card is
 * identical either way — only how much of it one strip holds changes.
 */
const CARD_SHOT_VIEWPORT = { width: WINDOW.panelWidth, height: 760 };

async function flipCard(panel, wantBack) {
  const isBack = async () => panel.evaluate((sel) => {
    const el = document.querySelector(sel)?.firstElementChild;
    return Boolean(el && /rotateY\(180/.test(el.style.transform || ''));
  }, CARD);

  if ((await isBack()) === wantBack) return;
  await panel.locator(CARD).click({ position: { x: 40, y: 40 } });
  await panel.waitForTimeout(800);
  if ((await isBack()) !== wantBack) throw new Error('card did not flip');
}

/* --------------------------------------------------------------------- runs ---- */

async function captureMain(ctx, worker, extensionId) {
  await seedSettings(worker);

  const article = await ctx.newPage();
  await article.setViewportSize(PAGE_VIEWPORT);
  await article.goto(CONTENT.articleUrl, { waitUntil: 'domcontentloaded' });
  await tidyWikipedia(article);
  await article.waitForTimeout(800);

  const panel = await openPanel(ctx, extensionId);

  await article.bringToFront();
  await selectWordOnPage(article, CONTENT.word, CONTENT.sentenceFragment);
  await article.screenshot({ path: raw('article.png') });
  log('wrote article.png');

  await waitForHandoff(panel, CONTENT.word);
  await panel.bringToFront();
  await generateGoodCard(panel, CONTENT.word);

  // Frame 02: the whole answer side, walked from top to bottom.
  const cardStrips = await captureCardStrips(panel);

  // Frame 01 shows the answer side: "the card is done" has to be visible as a finished
  // card, not as the question you have yet to answer.
  await focusCardOnAnswer(panel);
  await panel.screenshot({ path: raw('panel-card.png') });
  log('wrote panel-card.png');

  const hasImage = (await inspectCard(panel)).image;

  return { article, panel, hasImage, cardStrips };
}

/**
 * Frame 02 has to show the card as it actually is — every field the generator filled, not
 * the slice that happens to fit a side panel.
 *
 * The card cannot simply be photographed taller: StudyCard caps it at MAX_CARD_HEIGHT
 * (600px) and scrolls its content inside that box, so there is no window size at which the
 * whole answer side is on screen at once. It is walked instead — the card's own disclosure
 * opened, then one screenshot per scroll position, each landing on a boundary between the
 * card's blocks so no strip cuts through a line. compose.js stands the strips side by side,
 * which is what lets a tall card be drawn larger than life in a landscape frame instead of
 * shrunk into a corner of it.
 *
 * Returns how many strips were written.
 */
async function captureCardStrips(panel) {
  const normal = panel.viewportSize();
  await panel.setViewportSize(CARD_SHOT_VIEWPORT);
  await panel.waitForTimeout(1000);

  await flipCard(panel, true);
  await expandCardDetails(panel);
  await scrollCardToTop(panel);

  const plan = await panel.evaluate((sel) => {
    const card = document.querySelector(sel);
    const scroller = Array.from(card.querySelectorAll('*'))
      .find((el) => el.scrollHeight > el.clientHeight + 4);
    if (!scroller) return { stops: [0], visible: card.getBoundingClientRect().height };

    const view = scroller.clientHeight;
    const total = scroller.scrollHeight;
    const top = scroller.getBoundingClientRect().top - scroller.scrollTop;

    // Where the card's own blocks begin: the strips are cut on these lines.
    const boundaries = [0];
    scroller.querySelectorAll('*').forEach((el) => {
      if (!(el.textContent || '').trim() && el.tagName !== 'IMG') return;
      const y = el.getBoundingClientRect().top - top;
      if (y > 8 && y < total - 8) boundaries.push(y);
    });
    boundaries.sort((a, b) => a - b);

    // Evenly spaced scroll positions rather than greedy ones: with a greedy walk the last
    // strip gets clamped to the bottom of the content and repeats most of the strip before
    // it, which reads as a mistake. Spread the unavoidable overlap across every seam
    // instead, then nudge each stop onto a block boundary so no strip starts mid-sentence.
    const count = Math.max(1, Math.min(4, Math.ceil(total / view)));
    const stops = [];
    for (let i = 0; i < count; i += 1) {
      const even = count === 1 ? 0 : (i * (total - view)) / (count - 1);
      const near = boundaries
        .filter((y) => Math.abs(y - even) <= view * 0.12)
        .sort((a, b) => Math.abs(a - even) - Math.abs(b - even))[0];
      stops.push(Math.round(Math.max(0, Math.min(total - view, near ?? even))));
    }

    return { stops, view, total };
  }, CARD);

  log(`card content is ${Math.round(plan.total || 0)}px in a ${Math.round(plan.view || 0)}px box`
    + ` → ${plan.stops.length} strip(s)`);

  for (let i = 0; i < plan.stops.length; i += 1) {
    await panel.evaluate(({ sel, offset }) => {
      const card = document.querySelector(sel);
      const scroller = Array.from(card.querySelectorAll('*'))
        .find((el) => el.scrollHeight > el.clientHeight + 4);
      if (scroller) scroller.scrollTop = offset;
    }, { sel: CARD, offset: plan.stops[i] });
    await panel.waitForTimeout(400);
    await panel.locator(CARD).screenshot({ path: raw(`card-${i + 1}.png`) });
  }
  log(`wrote card-1..${plan.stops.length}.png`);

  await panel.setViewportSize(normal);
  await panel.waitForTimeout(1000);
  await flipCard(panel, true);
  return plan.stops.length;
}

/**
 * What the answer side actually ended up holding.
 *
 * Both faces stay in the DOM and the question side sets the word in larger type than the
 * answer side sets the translation, so everything here is read inside the answer side's
 * own scroller rather than across the whole card.
 */
async function inspectCard(panel) {
  return panel.evaluate((sel) => {
    const card = document.querySelector(sel);
    if (!card) return { examples: 0, translation: '', image: false };
    const scope = Array.from(card.querySelectorAll('*'))
      .find((el) => el.scrollHeight > el.clientHeight + 4) || card;

    const biggest = Array.from(scope.querySelectorAll('div, span, p'))
      .filter((el) => (el.textContent || '').trim() && el.clientHeight)
      .reduce((best, el) => {
        const size = parseFloat(getComputedStyle(el).fontSize) || 0;
        return size > (best.size || 0) ? { el, size } : best;
      }, {}).el;

    // The card hides the extra examples behind a disclosure, and says how many in its
    // label — cheaper and steadier than opening it just to count them.
    const text = scope.innerText || '';
    const more = text.match(/(\d+)\s+more examples?/);
    const shown = scope.querySelectorAll('li').length;
    return {
      examples: shown + (more ? Number(more[1]) : 0),
      translation: biggest ? biggest.textContent.trim() : '',
      image: Boolean(scope.querySelector('img[src]')),
    };
  }, CARD);
}

/**
 * Generation is not deterministic: a run can come back with no examples at all, or with the
 * Spanish word repeated where the translation belongs. Both are correct-ish cards and both
 * look broken in a store listing, so a card that falls short is thrown away and made again
 * through the same Create button a user would press.
 */
async function generateGoodCard(panel, word, attempts = 3) {
  let card;
  for (let attempt = 1; attempt <= attempts; attempt += 1) {
    if (attempt > 1) {
      await panel.locator('[role="dialog"] button[aria-label="Close"]').click().catch(() => {});
      await panel.waitForTimeout(800);
    }
    await generateCard(panel);
    await flipCard(panel, true);
    card = await inspectCard(panel);

    const faults = [];
    if (!card.translation) faults.push('no translation');
    if (card.translation.toLowerCase() === word.toLowerCase()) faults.push('translated to itself');
    if (card.examples < 2) faults.push(`${card.examples} example(s)`);
    if (OPENAI_KEY && !card.image) faults.push('no illustration');

    if (!faults.length) {
      log(`card: ${word} → ${card.translation} (${card.examples} examples`
        + `${card.image ? ', illustration' : ''})`);
      return card;
    }
    log(`attempt ${attempt}: ${faults.join(', ')}${attempt < attempts ? ' — making it again' : ''}`);
  }
  log(`WARNING: shipping an incomplete card for "${word}" after ${attempts} attempts`);
  return card;
}

/** Opens the card's own "N more examples · Grammar" disclosure, when it has one. */
async function expandCardDetails(panel) {
  const toggle = panel.locator(`${CARD} button[aria-expanded="false"]`).first();
  if (await toggle.count()) {
    await toggle.click();
    await panel.waitForTimeout(600);
  }
}

/**
 * A finished card is taller than the side panel, exactly as a user sees it. Frames 01, 04
 * and 05 have to say "the card is done" in one glance, so the visible slice is put on the
 * translation rather than left at the top of the card.
 */
async function focusCardOnAnswer(panel) {
  await panel.evaluate((sel) => {
    const card = document.querySelector(sel);
    if (!card) return;
    const scroller = Array.from(card.querySelectorAll('*'))
      .find((el) => el.scrollHeight > el.clientHeight + 8);
    if (!scroller) return;

    // The translation is the largest type on the answer side, which identifies it without
    // depending on a class name that a restyle would move.
    const translation = Array.from(scroller.querySelectorAll('div, span, p'))
      .filter((el) => (el.textContent || '').trim() && el.clientHeight)
      .reduce((biggest, el) => {
        const size = parseFloat(getComputedStyle(el).fontSize) || 0;
        return size > (biggest.size || 0) ? { el, size } : biggest;
      }, {}).el;
    if (!translation) return;

    // Land its bottom just inside the card, so the picture above it fills the rest — but
    // never scroll so far that the illustration is gone: half of it stays in shot even
    // when the translation runs to several lines.
    const offset = translation.getBoundingClientRect().bottom
      - scroller.getBoundingClientRect().bottom;
    const wanted = Math.max(0, scroller.scrollTop + offset + 14);

    const image = scroller.querySelector('img[src]');
    const ceiling = image
      ? scroller.scrollTop
        + (image.getBoundingClientRect().top - scroller.getBoundingClientRect().top)
        + image.clientHeight * 0.5
      : wanted;
    scroller.scrollTop = Math.min(wanted, Math.max(0, ceiling));
  }, CARD);
  await panel.waitForTimeout(400);
}

/** A flipped card keeps the scroll offset of whatever was open before it. */
async function scrollCardToTop(panel) {
  await panel.evaluate((sel) => {
    const card = document.querySelector(sel);
    if (!card) return;
    card.querySelectorAll('*').forEach((el) => { el.scrollTop = 0; });
  }, CARD);
  await panel.waitForTimeout(300);
}

/** What the compositor needs to know about the card it is framing. */
async function writeMeta(worker, hasImage, cardStrips) {
  const cards = await worker.evaluate(async () => {
    const items = await chrome.storage.local.get(['anki_stored_cards']);
    try { return JSON.parse(items.anki_stored_cards || '[]'); } catch { return []; }
  });
  const card = cards.find((item) => item && item.text === CONTENT.word)
    || cards[cards.length - 1] || null;

  fs.writeFileSync(raw('card.json'), JSON.stringify(card, null, 2));
  fs.writeFileSync(raw('meta.json'), JSON.stringify({
    hasImage,
    cardStrips,
    source: OPENAI_KEY ? 'openai' : 'trial',
    word: card && card.text,
    translation: card && card.translation,
    article: CONTENT.articleUrl,
    capturedAt: new Date().toISOString(),
  }, null, 2));
  log(`card: ${card && card.text} → ${card && card.translation}`);
}

/**
 * Frame 05: save the card, then study it on the Cards tab — the extension's own review
 * screen, with the answer shown and the four grading buttons and their intervals.
 *
 * A library of one card makes a thin screenshot, so a few more real cards are built by the
 * same card service the extension uses and written in the extension's own storage format.
 * Everything on screen is still the extension rendering its own data.
 */
async function captureReview(article, panel, worker) {
  await panel.getByRole('button', { name: 'Save card' }).click();
  await panel.waitForTimeout(1500);
  // Saving moves the first-run flow straight into its own review sheet; closing it is what
  // a user does before going to the library, and it also clears the overlay for the click
  // on the Cards tab below.
  await panel.locator('[role="dialog"] button[aria-label="Close"]').click().catch(() => {});
  await panel.waitForTimeout(500);

  await addLibraryCards(worker);
  await panel.reload();
  await panel.waitForSelector('nav, textarea, button', { timeout: 30_000 });
  await panel.waitForTimeout(1200);

  await panel.locator('button[title="View your saved cards"]').click();
  await panel.waitForTimeout(800);
  // The button carries its due count ("Study 3"), so the name is matched loosely.
  await panel.getByRole('button', { name: 'Study' }).first().click();
  await panel.waitForTimeout(800);
  await panel.getByRole('button', { name: 'Show answer' }).click();
  await panel.waitForTimeout(1200);
  await focusCardOnAnswer(panel);
  await panel.screenshot({ path: raw('panel-review.png') });
  log('wrote panel-review.png');

  // The page behind a review is just the page you were reading; keeping the same article
  // makes 05 read as a continuation of 01 rather than a different product.
  await article.evaluate(() => window.getSelection().removeAllRanges());
  await article.screenshot({ path: raw('review-page.png') });
  log('wrote review-page.png');
}

/** Words a Spanish learner would actually have in a deck, cards built by the real service. */
const LIBRARY_WORDS = ['madrugar', 'aprovechar', 'echar de menos'];

/**
 * The library cards are given a schedule that puts them a few days out, the way cards that
 * have already been reviewed sit in a real deck. That also settles which card frame 05
 * shows: the study queue takes what is due, so the one card that is still new — the one
 * just made from the page, illustration and all — is the card under review.
 */
const scheduledAhead = (days) => {
  const due = new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString();
  const lastReview = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  return {
    srs_due_at: due,
    srs_interval_days: days,
    srs_ease: 2.5,
    srs_reps: 2,
    srs_lapses: 0,
    srs_last_review_at: lastReview,
  };
};

async function addLibraryCards(worker) {
  const built = [];
  for (const text of LIBRARY_WORDS) {
    try {
      const response = await fetch('https://api-cards.vaultonote.com/trial/cards', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          text,
          target_language: CONTENT.targetLanguage,
          source_language: 'es',
          installation_id: crypto.randomUUID(),
          request_id: crypto.randomUUID(),
        }),
      });
      const data = await response.json();
      const card = data.card;
      if (!card || !card.translation) throw new Error('incomplete card');
      built.push({
        id: crypto.randomUUID(),
        mode: 'language-learning',
        text,
        front: text,
        translation: card.translation,
        transcription: card.transcription || '',
        linguisticInfo: card.grammar_note || '',
        examples: (card.examples || []).map((e) => [e.text, e.translation]),
        examplesAudio: (card.examples || []).map(() => null),
        createdAt: new Date(Date.now() - (built.length + 1) * 86_400_000).toISOString(),
        exportStatus: 'not_exported',
        srsState: scheduledAhead(2 + built.length),
      });
    } catch (error) {
      log(`skipped library card "${text}": ${error.message}`);
    }
  }
  if (!built.length) return;

  await worker.evaluate(async (extra) => {
    const items = await chrome.storage.local.get(['anki_stored_cards']);
    let cards = [];
    try { cards = JSON.parse(items.anki_stored_cards || '[]'); } catch { cards = []; }
    await chrome.storage.local.set({
      anki_stored_cards: JSON.stringify([...cards, ...extra]),
    });
  }, built);
  log(`added ${built.length} more real cards to the library`);
}

/**
 * Frame 04: the same hand-off, on a different site and a different kind of reading — a
 * novel rather than an encyclopedia. Same code path as frame 01, which is the point of the
 * frame: nothing about the page matters.
 */
async function captureSecondPage(ctx, worker, extensionId) {
  // Frame 04 can be captured on its own (--only=page2), so it seeds the same settings
  // rather than relying on frame 01 having run first.
  await seedSettings(worker);

  const page = await ctx.newPage();
  await page.setViewportSize(PAGE_VIEWPORT);
  // A whole novel in one document: give it time to lay out before anything is measured.
  await page.goto(SECOND_PAGE.url, { waitUntil: 'load', timeout: 120_000 });
  await page.waitForTimeout(5000);

  const panel = await openPanel(ctx, extensionId);
  await page.bringToFront();

  await selectWordOnPage(page, SECOND_PAGE.word, SECOND_PAGE.sentenceFragment);
  await page.screenshot({ path: raw('page2.png') });
  log('wrote page2.png');

  await waitForHandoff(panel, SECOND_PAGE.word);
  await panel.bringToFront();
  await generateGoodCard(panel, SECOND_PAGE.word);
  await focusCardOnAnswer(panel);
  await panel.screenshot({ path: raw('panel-page2.png') });
  log('wrote panel-page2.png');
}

/* --------------------------------------------------------------------- main ---- */

(async () => {
  const { ctx, worker, extensionId, userDataDir } = await launch();
  try {
    let article; let panel; let hasImage = false; let cardStrips = 0;
    if (only.includes('main')) {
      ({ article, panel, hasImage, cardStrips } = await captureMain(ctx, worker, extensionId));
    }
    if (only.includes('review') && panel) {
      await captureReview(article, panel, worker);
    }
    if (only.includes('main')) {
      await writeMeta(worker, hasImage, cardStrips);
    }
    if (only.includes('page2')) {
      await captureSecondPage(ctx, worker, extensionId);
    }
    log('raw captures in', paths.raw);
    if (flag('keep-open')) {
      log('--keep-open: leaving the browser up, Ctrl+C to finish');
      await new Promise(() => {});
    }
  } finally {
    if (!flag('keep-open')) {
      await ctx.close();
      fs.rmSync(userDataDir, { recursive: true, force: true });
    }
  }
})().catch((error) => {
  console.error('[capture] failed:', error);
  process.exit(1);
});
