import React from 'react';
import { FaTimes, FaCheck, FaSave, FaEdit } from 'react-icons/fa';
import ResultDisplay from '../ResultDisplay';
import { StoredCard } from '../../store/reducers/cards';
import { Modes } from '../../constants';
import Loader from '../Loader';

interface BatchPreviewModalProps {
    show: boolean;
    previewCards: StoredCard[];
    currentPreviewIndex: number;
    savedCardIndices: Set<number>;
    loadingAccept: boolean;
    onClose: () => void;
    onNext: () => void;
    onPrev: () => void;
    onSaveCurrent: () => void;
    onRecreateCurrent: () => void;
    onRejectAll: () => void;
    onAcceptAll: () => void;
    onUpdateBack: (newBack: string) => void;
}

const BatchPreviewModal: React.FC<BatchPreviewModalProps> = ({
    show,
    previewCards,
    currentPreviewIndex,
    savedCardIndices,
    loadingAccept,
    onNext,
    onPrev,
    onSaveCurrent,
    onRecreateCurrent,
    onRejectAll,
    onAcceptAll,
    onUpdateBack,
}) => {
    if (!show) return null;

    const currentCard = previewCards[currentPreviewIndex];

    return (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/50 p-5">
            <div className="flex max-h-[90vh] w-full max-w-[600px] flex-col overflow-hidden rounded-xl border border-gray-100 bg-white shadow-2xl">
                <div className="flex items-center border-b border-gray-100 px-6 py-5">
                    <div className="flex-1">
                        <h3 className="m-0 text-lg font-semibold text-black">Review Cards</h3>
                        <p className="m-0 mt-1 text-[13px] text-gray-500">{previewCards.length} cards generated by AI</p>
                    </div>
                    <button
                        onClick={onRejectAll}
                        className="rounded p-1 text-lg text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-600"
                    >
                        <FaTimes />
                    </button>
                </div>

                {previewCards.length > 1 && (
                    <div className="flex items-center justify-center border-b border-gray-100 bg-gray-50 px-6 py-3">
                        <div className="flex items-center gap-3">
                            <button
                                onClick={onPrev}
                                disabled={currentPreviewIndex === 0}
                                className="rounded-md border border-gray-200 bg-white px-3 py-1.5 text-sm font-medium text-gray-600 disabled:cursor-not-allowed disabled:text-gray-300"
                            >
                                ←
                            </button>

                            <div className="text-[13px] font-medium text-gray-600">
                                {currentPreviewIndex + 1} of {previewCards.length}
                            </div>

                            <button
                                onClick={onNext}
                                disabled={currentPreviewIndex === previewCards.length - 1}
                                className="rounded-md border border-gray-200 bg-white px-3 py-1.5 text-sm font-medium text-gray-600 disabled:cursor-not-allowed disabled:text-gray-300"
                            >
                                →
                            </button>
                        </div>
                    </div>
                )}

                <div className="flex-1 overflow-auto bg-white p-4">
                    {currentCard && (
                        <ResultDisplay
                            front={currentCard.front || null}
                            back={currentCard.back || null}
                            translation={null}
                            examples={[]}
                            imageUrl={currentCard.imageUrl || null}
                            image={currentCard.image || null}
                            linguisticInfo=""
                            transcription={null}
                            wordAudio={currentCard.wordAudio || null}
                            onNewImage={() => {}}
                            onNewExamples={() => {}}
                            onAccept={onSaveCurrent}
                            onViewSavedCards={() => {}}
                            loadingNewImage={false}
                            loadingNewExamples={false}
                            loadingAccept={loadingAccept}
                            createdAt={new Date()}
                            mode={Modes.GeneralTopic}
                            shouldGenerateImage={false}
                            isSaved={savedCardIndices.has(currentPreviewIndex)}
                            isEdited={false}
                            isGeneratingCard={false}
                            hideActionButtons={true}
                            setBack={onUpdateBack}
                        />
                    )}
                </div>

                <div className="flex flex-col gap-3 border-t border-gray-100 bg-gray-50 px-5 py-4">
                    <div className="flex justify-center gap-2">
                        <button
                            onClick={onSaveCurrent}
                            disabled={loadingAccept || savedCardIndices.has(currentPreviewIndex)}
                            className="flex min-w-[100px] items-center justify-center gap-1.5 rounded-md border border-gray-200 px-4 py-2 text-sm font-medium text-gray-700 disabled:cursor-not-allowed disabled:opacity-70"
                        >
                            {savedCardIndices.has(currentPreviewIndex) ? (
                                <><FaCheck size={14} /> Saved</>
                            ) : (
                                <><FaSave size={14} /> Save</>
                            )}
                        </button>

                        <button
                            onClick={onRecreateCurrent}
                            disabled={loadingAccept}
                            className="flex min-w-[100px] items-center justify-center gap-1.5 rounded-md border border-amber-500 px-4 py-2 text-sm font-medium text-amber-600 transition-colors hover:bg-amber-500 hover:text-white disabled:cursor-not-allowed disabled:opacity-70"
                        >
                            <FaEdit size={14} />
                            Improve
                        </button>
                    </div>

                    <div className="flex justify-center gap-2">
                        <button
                            onClick={onRejectAll}
                            disabled={loadingAccept}
                            className="min-w-[100px] rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-600 hover:bg-gray-100 disabled:cursor-not-allowed disabled:opacity-70"
                        >
                            Cancel
                        </button>

                        <button
                            onClick={onAcceptAll}
                            disabled={loadingAccept}
                            className="flex min-w-[140px] items-center justify-center gap-2 rounded-md bg-blue-600 px-6 py-2 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-blue-700 disabled:cursor-not-allowed disabled:bg-gray-400"
                        >
                            {loadingAccept ? (
                                <><Loader type="spinner" size="small" inline color="#ffffff" /> Saving...</>
                            ) : (
                                <><FaCheck size={14} /> Save All ({previewCards.length})</>
                            )}
                        </button>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default BatchPreviewModal;
